prefix roh: <http://w3id.org/roh#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>


SELECT distinct ?authorName  ?document
 WHERE { 
    ?document roh:correspondingAuthor ?URI_author.
    ?URI_author foaf:name ?authorName;
  }
  