prefix vivo: <http://w3id.org/roh/mirror/vivo#>
prefix roh: <http://w3id.org/roh#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix gn: <http://w3id.org/roh/mirror/geonames#>
prefix vcard: <http://w3id.org/roh/mirror/vcard#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>

SELECT
  ?author  ?address ?extendedAddres ?city ?PostalCode 
WHERE {
  ?publication   roh:correspondingAuthor ?person.
  ?person roh:hasContactInfo ?individual;
  foaf:name ?author.
  ?individual vcard:hasAddress ?adress.
  ?adress 
    vcard:extended-address  ?extendedAddres;
    vcard:locality ?city;
    vcard:postal-code ?PostalCode;
    vcard:street-address ?address.
}
