
prefix vivo: <http://w3id.org/roh/mirror/vivo#>
prefix roh: <http://w3id.org/roh#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix foaf: <http://w3id.org/roh/mirror/foaf#>
prefix gn: <http://w3id.org/roh/mirror/geonames#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>


SELECT
 ?publication  ?metric ?author
WHERE {
  ?publication         a roh:PhDThesis ;
    roh:hasMetric ?metric;
    roh:correspondingAuthor ?person.
    ?person foaf:name ?author.
    }


