# ACTIVIDADES!

prefix roh: <http://w3id.org/roh#>
PREFIX foaf: <http://w3id.org/roh/mirror/foaf#>
PREFIX vivo: <http://w3id.org/roh/mirror/vivo#>
prefix ro: <http://w3id.org/roh/mirror/obo/ro#>
prefix bibo: <http://w3id.org/roh/mirror/bibo#>
prefix vcard: <http://w3id.org/roh/mirror/vcard#>
prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#>


SELECT distinct ?conference ?title ?city ?document ?titleOfDocument ?PersonName
Where {
    ?conference a bibo:Conference; 
    Optional{?conference 
            roh:title ?title;} 

           Optional{?conference 
     vcard:locality ?city.}   
      Optional{?conference 

            bibo:presents ?document.
      Optional{
            ?document roh:title ?titleOfDocument.}Optional{?document
            roh:seqOfAuthors ?list.
        ?list rdfs:member ?person.
        ?person foaf:name ?PersonName}
    }
  }